################
### MONITORS ###
################

# Use 'hyprctl monitors all' to see all connected monitors info 

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, 2880x1800@120.00, 0x0, 2
monitor = DP-1, highres, -1920x0, 2 # ASUS 27" Horizontal
monitor = HDMI-A-1, highres, -1920x0, 2 # HDMI
# monitor = DP-4, 1920x1080@60, -2460x0, 2# Dell 24" Vertical

# hl.monitor({
#   output = "eDP-1",
#   mode = "2880x1800@120.00",
#   position = "0x0",
#   scale = 2,
# })